### ISSUE TITLE
NoHandleError in 1.3.1

### ISSUE THREAD

**Issue by effigies** [pauldmccarthy/indexed_gzip#40]
I'm going to release a nibabel soon, but just FYI:

```
UNEXPECTED EXCEPTION: NoHandleError()
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/doctest.py", line 1329, in __run
    compileflags, 1), test.globs)
  File "<doctest nibabel.dataobj_images.DataobjImage.get_data[19]>", line 1, in <module>
  File "/home/travis/build/nipy/nibabel/venv/lib/python3.7/site-packages/nibabel-3.1.0+205.g8ed5f74-py3.7.egg/nibabel/deprecator.py", line 162, in deprecated_func
    return func(*args, **kwargs)
  File "/home/travis/build/nipy/nibabel/venv/lib/python3.7/site-packages/nibabel-3.1.0+205.g8ed5f74-py3.7.egg/nibabel/dataobj_images.py", line 207, in get_data
    data = np.asanyarray(self._dataobj)
  File "/home/travis/build/nipy/nibabel/venv/lib/python3.7/site-packages/numpy/core/_asarray.py", line 136, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/home/travis/build/nipy/nibabel/venv/lib/python3.7/site-packages/nibabel-3.1.0+205.g8ed5f74-py3.7.egg/nibabel/arrayproxy.py", line 391, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())
  File "/home/travis/build/nipy/nibabel/venv/lib/python3.7/site-packages/nibabel-3.1.0+205.g8ed5f74-py3.7.egg/nibabel/arrayproxy.py", line 358, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
  File "/home/travis/build/nipy/nibabel/venv/lib/python3.7/site-packages/nibabel-3.1.0+205.g8ed5f74-py3.7.egg/nibabel/arrayproxy.py", line 337, in _get_unscaled
    mmap=self._mmap)
  File "/home/travis/build/nipy/nibabel/venv/lib/python3.7/site-packages/nibabel-3.1.0+205.g8ed5f74-py3.7.egg/nibabel/volumeutils.py", line 508, in array_from_file
    offset=offset)
  File "/home/travis/build/nipy/nibabel/venv/lib/python3.7/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
  File "indexed_gzip/indexed_gzip.pyx", line 311, in indexed_gzip.indexed_gzip._IndexedGzipFile.fileno
indexed_gzip.indexed_gzip.NoHandleError
```

**Comment by effigies** [comment]
https://travis-ci.com/github/nipy/nibabel/jobs/354026554

**Comment by pauldmccarthy** [comment]
Yes, I noticed this as well. Haven't looked into it yet, but I am confused that it wasn't happening to me when running locally - I've only seen it in CI. Will look into it today.

**Comment by pauldmccarthy** [comment]
Hmm, I'm not sure if there's a solution to this one ... we may have to live with the fact that `nibabel<=3.1.0` is incompatible with  `indexed_gzip>=1.3.0` (edit: possible solution outlined at the bottom). Minimal reproducible example (with `nibabel==3.1.0`, `indexed_gzip==1.3.1`):

```
import numpy as np
import nibabel as nib

i = nib.load('any_image.nii.gz')
np.asanyarray(i.dataobj)
np.asanyarray(i.dataobj)
```

This error is occurring on the _second_ attempt to load data from an `IndexedGzipFile` object. 

On the first attempt, `np.memmap` raises a `ValueError` from [this call to `fid.seek`](https://github.com/numpy/numpy/blob/ae6ba5d215451273990f2826f2cf28f091d71446/numpy/core/memmap.py#L228) - it raises a `ValueError` (in indexed_gzip 1.3.1, or a `NotCoveredError` in 1.3.0) because the index hasn't been built, and `SEEK_END` is not yet possible.

But then on the second attempt, an index for the file has been built, so the `seek` call passes. But then [the call to `fid.fileno`](https://github.com/numpy/numpy/blob/ae6ba5d215451273990f2826f2cf28f091d71446/numpy/core/memmap.py#L264) raises a `NoHandleError`, because the `IndexedGzipFile` does not maintain a persistent file handle.

Out of curiosity, I changed the above example to:

```.
import numpy as np
import nibabel as nib

i = nib.load('any_image.nii.gz', keep_file_open=True)
np.asanyarray(i.dataobj)
np.asanyarray(i.dataobj)
```

This works! It works because, on the second attempt, [the `mmap.mmap` call](https://github.com/numpy/numpy/blob/ae6ba5d215451273990f2826f2cf28f091d71446/numpy/core/memmap.py#L264) raises a `ValueError`:

```
ValueError: mmap length is greater than file size
> numpy/core/memmap.py(264)__new__()
-> mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
```

With a very sensible error message, which is nice. We're now back in the situation where [`nibabel` catches this `ValueError`](https://github.com/nipy/nibabel/blob/a48c95443f4ce2f36f774469415fd2aea284855a/nibabel/volumeutils.py#L511), and falls back to file-based access to retrieve the data. 

Wow, I feel like we've come full circle on this :)

But back to the more immediate issue. I cant think of a way to make `indexed_gzip>=1.3.0` compatible with `nibabel<=3.1.0` ... unless we go with your [earlier suggestion](https://github.com/pauldmccarthy/indexed_gzip/issues/38#issuecomment-649718538) of changing the `indexed_gzip` error types to sub-class from `ValueError`. Now that I think about it, I'm not really against this idea at all. What do you think?

In any case, I'm definitely going to add some regression tests into `indexed_gzip` to make sure that it plays nicely with `nibabel`. I should have done this a while ago.

**Comment by pauldmccarthy** [comment]
I can imagine a scenario where somebody was using `keep_file_open=True`, and was loading a `.nii.gz` file which somehow has the same compressed and uncompressed sizes, so `mmap.mmap` would work, and they would get a data array filled with compressed garbage. This would be hilarious, but I think also extremely unlikely.
