### ISSUE TITLE
Trailing null bytes cause errors when reading

### ISSUE THREAD

**Issue by epicfaace** [pauldmccarthy/indexed_gzip#69]
I'm running into an interesting error in which trailing null bytes in a gzip file cause errors when reading a gzip file using `indexed_gzip`. Here's the closest reproduction (the trailing null bytes occur when I'm using bsdtar to tar and gzip a directory and print it to stdout, because in that case, bsdtar pads the gz file with null bytes):

```python
import tempfile
import subprocess
import shutil
from indexed_gzip import IndexedGzipFile

with tempfile.TemporaryDirectory() as tmpdir:
    with open(tmpdir + "/" + "tempfile", "wb") as f:
        f.write(b"hello world")
    
    # Make sure you're using bsdtar here, since bsdtar pads the gz file with null bytes
    # if the .tar.gz file is written to stdout.
    fileobj = subprocess.Popen(['tar', 'czf', '-', '-C', tmpdir, '.'], stdout=subprocess.PIPE).stdout
    with open('/tmp/out1.tar.gz', 'w+') as f:
        f.truncate(0)

    subprocess.Popen(['tar', 'czf', '/tmp/out2.tar.gz', '-C', tmpdir, '.'], stdout=subprocess.PIPE).stdout.read()
    with open('/tmp/out1.tar.gz', 'wb') as f:
        shutil.copyfileobj(fileobj, f)
    
    with open('/tmp/out1.tar.gz', 'rb') as f1, open('/tmp/out2.tar.gz', 'rb') as f2:
        igz1 = IndexedGzipFile(fileobj=f1)
        igz1.read()
        # the above line fails (nondeterministically, but most of the time) with the following stack trace:
        # Traceback (most recent call last):
        # File "test.py", line 22, in <module>
        #     igz1.read()  # this fails
        # File "indexed_gzip/indexed_gzip.pyx", line 647, in indexed_gzip.indexed_gzip._IndexedGzipFile.read
        #     with self.__file_handle():
        # File "indexed_gzip/indexed_gzip.pyx", line 662, in indexed_gzip.indexed_gzip._IndexedGzipFile.read
        #     raise ZranError('zran_read returned error '
        # indexed_gzip.indexed_gzip.ZranError: zran_read returned error (-3)
        # zran_free

        igz2 = IndexedGzipFile(fileobj=f2)
        igz2.read()  # this never fails
```

You can see the contents of /tmp/out1.tar.gz (padded with null bytes, nondeterministically fails) versus /tmp/out2.tar.gz (not padded, always works) here:

```bash
(venv) epicfaace@ashwins-mbp indexed_gzip % od -t x1 /tmp/out1.tar.gz
0000000    1f  8b  08  00  19  83  a0  60  00  03  ed  d1  41  0a  c2  30
0000020    10  05  d0  1c  65  4e  d0  fe  49  26  f5  3c  a1  26  58  88
0000040    b4  d4  8a  d7  37  b4  45  41  68  57  46  11  f3  36  7f  33
0000060    84  3f  99  aa  56  d9  01  38  00  34  67  63  e7  84  96  25
0000100    57  c4  02  0b  06  8b  61  02  6b  6d  58  91  cd  5f  4d  a9
0000120    eb  65  72  63  aa  e2  87  ae  0d  ce  b5  7e  63  2e  8d  85
0000140    b0  f3  ce  ba  c7  23  7f  44  55  4f  fe  3c  84  2e  6e  ed
0000160    fd  06  e9  3f  1a  91  9d  fb  b3  79  b9  bf  49  73  8a  90
0000200    af  d2  d3  9f  df  ff  e4  63  ec  e9  d6  8f  f1  f8  ed  2a
0000220    45  51  14  c5  07  dd  01  c1  00  32  68  00  0a  00  00  00
0000240    00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
*
0024000
(venv) epicfaace@ashwins-mbp indexed_gzip % od -t x1 /tmp/out2.tar.gz
0000000    1f  8b  08  00  19  83  a0  60  00  03  ed  d1  41  0a  c2  30
0000020    10  05  d0  1c  65  4e  d0  fe  49  26  f5  3c  a1  26  58  88
0000040    b4  d4  8a  d7  37  b4  45  41  68  57  46  11  f3  36  7f  33
0000060    84  3f  99  aa  56  d9  01  38  00  34  67  63  e7  84  96  25
0000100    57  c4  02  0b  06  8b  61  02  6b  6d  58  91  cd  5f  4d  a9
0000120    eb  65  72  63  aa  e2  87  ae  0d  ce  b5  7e  63  2e  8d  85
0000140    b0  f3  ce  ba  c7  23  7f  44  55  4f  fe  3c  84  2e  6e  ed
0000160    fd  06  e9  3f  1a  91  9d  fb  b3  79  b9  bf  49  73  8a  90
0000200    af  d2  d3  9f  df  ff  e4  63  ec  e9  d6  8f  f1  f8  ed  2a
0000220    45  51  14  c5  07  dd  01  c1  00  32  68  00  0a  00  00    
0000237
```

**Comment by epicfaace** [comment]
Note that [bsdtar's documentation does mention](https://opensource.apple.com/source/libarchive/libarchive-33.20.2/libarchive/doc/text/bsdtar.1.txt.auto.html) this behavior of padding gz files:

```
     All archive output is written in correctly-sized blocks, even if the out-
     put is being compressed.  Whether or not the last output block is padded
     to a full block size varies depending on the format and the output
     device.  For tar and cpio formats, the last block of output is padded to
     a full block size if the output is being written to standard output or to
     a character or block device such as a tape drive.	If the output is being
     written to a regular file, the last block will not be padded.  Many com-
     pressors, including gzip(1) and bzip2(1), complain about the null padding
     when decompressing an archive created by tar, although they still extract
     it correctly.
```

I'm a bit at a loss as to why padding a gz file with null bytes would cause issues when using it with IndexedGzipFile. Any thoughts @pauldmccarthy ?

**Comment by epicfaace** [comment]
Okay, I think I found a much simpler reproduction of this issue:

```
import gzip
from io import BytesIO

igz1 = IndexedGzipFile(fileobj=BytesIO(gzip.compress(b"hello world") + b"\0" * 10))
igz1.read()
```

This consistently gives the error: "zran_read returned error (-3)"

**Comment by epicfaace** [comment]
This is how cpython handles it: https://github.com/python/cpython/blob/main/Lib/gzip.py#L534-L541

**Comment by pauldmccarthy** [comment]
Hi @epicfaace, thanks for doing the research. I didn't know about padding bytes, as I've always gone to the [gzip RFC](https://datatracker.ietf.org/doc/html/rfc1952), which doesn't mention them at all. The ref in the cpython code (http://www.gzip.org/#faq8) doesn't seem to exist anymore, but I did find this: https://www.gnu.org/software/gzip/manual/gzip.html#Tapes

This has actually reminded me that I intended to add a CRC check into `indexed_gzip` - I'll have a play with your #70, and see if the code can be cleaned up a bit, and CRC checking implemented
